include: package:very_good_analysis/analysis_options.yaml

linter: 
  rules:
    prefer_relative_imports: true
    avoid_relative_lib_imports: false
    always_use_package_imports: false
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    one_member_abstracts: false

analyzer:
  plugins:
    - custom_lint
