name: flutter_hmmm
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  animate_gradient: ^0.0.3
  archive: ^4.0.4
  choice: ^2.3.2
  collection: ^1.19.1
  cross_file: ^0.3.4+2
  dart_mappable: ^4.4.0
  desktop_drop: ^0.5.0
  fast_immutable_collections: ^11.0.3
  file_selector: ^1.0.3
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  flutter_staggered_grid_view: ^0.7.0
  fpdart: ^1.1.1
  gap: ^3.0.1
  hooks_riverpod: ^2.6.1
  leak_tracker: ^10.0.8
  path: ^1.9.0
  path_provider: ^2.1.5
  pixels: ^1.0.1
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.5.2
  talker: ^4.6.14
  talker_flutter: ^4.7.1
  talker_riverpod_logger: ^4.6.14

dev_dependencies:
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  dart_mappable_builder: ^4.4.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Retro Computer
      fonts:
        - asset: fonts/retro_computer_personal_use.ttf
